using WCSharp.Shared.Data;

/// <summary>
/// This class is auto-generated by WCSharp.ConstantGenerator.
/// </summary>
public static class Regions
{
	public static Rectangle Player_1 { get; set; } = new Rectangle(-19680f, 18208f, -18464f, 19424f);
	public static Rectangle Player_2 { get; set; } = new Rectangle(-18016f, 18208f, -16800f, 19424f);
	public static Rectangle Player_3 { get; set; } = new Rectangle(-16352f, 18208f, -15136f, 19424f);
	public static Rectangle Player_4 { get; set; } = new Rectangle(-14688f, 18208f, -13472f, 19424f);
	public static Rectangle Player_5 { get; set; } = new Rectangle(-13024f, 18208f, -11808f, 19424f);
	public static Rectangle Player_6 { get; set; } = new Rectangle(-11360f, 18208f, -10144f, 19424f);
	public static Rectangle Player_7 { get; set; } = new Rectangle(-9696f, 18208f, -8480f, 19424f);
	public static Rectangle Player_8 { get; set; } = new Rectangle(-8032f, 18208f, -6816f, 19424f);
	public static Rectangle Player_9 { get; set; } = new Rectangle(-6496f, 18208f, -5280f, 19424f);
	public static Rectangle Player_10 { get; set; } = new Rectangle(-4992f, 18208f, -3776f, 19424f);
	public static Rectangle Nation_Picker { get; set; } = new Rectangle(2592f, 18688f, 2912f, 18976f);

}